### ISSUE TITLE
Can I reuse your content?

### ISSUE THREAD

**Issue by cosmicdreams** [joshkoenig/headless-drupal-angular#1]
I'd like to be able to reuse the same content you are in setting up future demos.  I'm currently working on a Web Components based demo that doesn't use angular.  If the read permissions are set liberally enough on your demo site I should be able to access your content without much of a performance penalty.

My fork is here: https://github.com/cosmicdreams/headless-drupal-angular

**Comment by joshkoenig** [comment]
Feel free to use what I have. It's a collection of clever ipsum generators and some photos from image-ipsum. :)

Coming up with an even better "gold standard" for demo content would certainly be nice to help get more people involved. 

Want to make a pull request for the `bower.json` work? That's literally at the top of my TODO list but I didn't want to block on getting this out.

**Comment by cosmicdreams** [comment]
will do.

If I just use your Rest Service for it's data, I expect CORS to block me:
http://enable-cors.org/server.html

I've seen chrome step up it's implementation of CORS and break a number sites that freely use XSS and other unwanted techniques.  

I'll give it a shot though, maybe I'll get lucky.

**Comment by cosmicdreams** [comment]
my bower.json will be different that yours.  You would be better off if you just did a bower init in the the app directory.  Bower will detect the libraries you have used and include them as dependencies.

Then you can git rm -r --cached your bower_components directory and ignore that dir in your .gitignore so you don't accidentally include it.

**Comment by joshkoenig** [comment]
Ah, I didn't understand what you meant about "using my content".

I will need to look into this a little further. It should be easy to get Drupal 8 to start including a `Access-Control-Allow-Origin: *` header in all responses, and then I'll want to set up a site that I won't mess around with so people can use it as their own backend.

Thanks for the bower tip. I did not know it was that easy! :)

**Comment by joshkoenig** [comment]
I've opened it up so you can use my Drupal 8 installation as the basis for getting started.

As I develop the demo, I'll keep that site up to date. That means if you are doing your own demo you should really set up your own site so it doesn't get broken as I make advancements/changes. 

However, this should really help front-end developer who want to play with the concept get started without having to set up Drupal. :)
